use triovist

/*Checking and creating primary keys*/
IF OBJECT_ID('dbo.[PK__Reference23294_VT26527]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._Reference23294_VT26527 ADD CONSTRAINT
	PK__Reference23294_VT26527 PRIMARY KEY NONCLUSTERED 
	(
	_Reference23294_IDRRef,
	_KeyField
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


ALTER TABLE dbo._Reference23294_VT26527 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__InfoRg24088]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._InfoRg24088 ADD CONSTRAINT
	PK__InfoRg24088 PRIMARY KEY CLUSTERED 
	(
	_Period
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._InfoRg24088 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__Const21579]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._Const21579 ADD CONSTRAINT
	PK__Const21579 PRIMARY KEY NONCLUSTERED 
	(
	_RecordKey
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._Const21579 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__Const21336]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._Const21336 ADD CONSTRAINT
	PK__Const21336 PRIMARY KEY NONCLUSTERED 
	(
	_RecordKey
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._Const21336 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__Const21338]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._Const21338 ADD CONSTRAINT
	PK__Const21338 PRIMARY KEY NONCLUSTERED 
	(
	_RecordKey
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._Const21338 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__Const21165]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._Const21165 ADD CONSTRAINT
	PK__Const21165 PRIMARY KEY NONCLUSTERED 
	(
	_RecordKey
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

ALTER TABLE dbo._Const21165 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__Const21167]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._Const21167 ADD CONSTRAINT
	PK__Const21167 PRIMARY KEY NONCLUSTERED 
	(
	_RecordKey
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._Const21167 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__InfoRg22353]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._InfoRg22353 ADD CONSTRAINT
	PK__InfoRg22353 PRIMARY KEY NONCLUSTERED 
	(
	_Fld22354
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._InfoRg22353 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__AccumRg25104]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._AccumRg25104 ADD CONSTRAINT
	PK__AccumRg25104 PRIMARY KEY NONCLUSTERED 
	(
	_Period,
	_RecorderTRef,
	_RecorderRRef,
	_LineNo,
	_Active,
	_RecordKind,
	_Fld25105RRef
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._AccumRg25104 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__AccumRg25110]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._AccumRg25110 ADD CONSTRAINT
	PK__AccumRg25110 PRIMARY KEY NONCLUSTERED 
	(
	_Period,
	_RecorderTRef,
	_RecorderRRef,
	_LineNo,
	_Active,
	_RecordKind,
	_Fld25111RRef,
	_Fld25112RRef,
	_Fld25202,
	_Fld25203
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._AccumRg25110 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__InfoRg23830]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._InfoRg23830 ADD CONSTRAINT
	PK__InfoRg23830 PRIMARY KEY NONCLUSTERED 
	(
	_Fld23831RRef,
	_Fld23832,
	_Fld23833RRef,
	_Fld23834
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._InfoRg23830 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__AccumRg21407]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._AccumRg21407 ADD CONSTRAINT
	PK__AccumRg21407 PRIMARY KEY NONCLUSTERED 
	(
	_Period,
	_RecorderTRef,
	_RecorderRRef,
	_LineNo,
	_Active,
	_RecordKind,
	_Fld21408RRef,
	_Fld21410_TYPE,
	_Fld21410_RTRef,
	_Fld21410_RRRef,
	_Fld23568RRef,
	_Fld21424
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._AccumRg21407 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__InfoRgSL26678]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._InfoRgSL26678 ADD CONSTRAINT
	PK__InfoRgSL26678 PRIMARY KEY NONCLUSTERED 
	(
	_Period,
	_Fld14558RRef
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._InfoRgSL26678 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__Reference23294_VT23309]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._Reference23294_VT23309 ADD CONSTRAINT
	PK__Reference23294_VT23309 PRIMARY KEY NONCLUSTERED 
	(
	_Reference23294_IDRRef,
	_KeyField
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._Reference23294_VT23309 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__Reference114_VT23370]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._Reference114_VT23370 ADD CONSTRAINT
	PK__Reference114_VT23370 PRIMARY KEY NONCLUSTERED 
	(
	_Reference114_IDRRef,
	_KeyField
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._Reference114_VT23370 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__AccumRgT21444]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._AccumRgT21444 ADD CONSTRAINT
	PK__AccumRgT21444 PRIMARY KEY NONCLUSTERED 
	(
	_Period,
	_Fld21408RRef,
	_Fld21410_TYPE,
	_Fld21410_RTRef,
	_Fld21410_RRRef,
	_Fld23568RRef,
	_Fld21424,
	_Splitter
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._AccumRgT21444 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__Reference23612_VT27054]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._Reference23612_VT27054 ADD CONSTRAINT
	PK__Reference23612_VT27054 PRIMARY KEY NONCLUSTERED 
	(
	_Reference23612_IDRRef,
	_KeyField,
	_LineNo27055
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._Reference23612_VT27054 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__InfoRg23320]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._InfoRg23320 ADD CONSTRAINT
	PK__InfoRg23320 PRIMARY KEY NONCLUSTERED 
	(
	_Fld23321,
	_Fld23322RRef,
	_Fld23383RRef,
	_Fld23323RRef,
	_Fld23324RRef,
	_Fld23325RRef,
	_Fld25515,
	_Fld23665RRef
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._InfoRg23320 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__InfoRg21711]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._InfoRg21711 ADD CONSTRAINT
	PK__InfoRg21711 PRIMARY KEY NONCLUSTERED 
	(
	_Period,
	_Fld21712,
	_Fld21713,
	_Fld21714,
	_Fld21715,
	_Fld25549
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._InfoRg21711 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__Reference23612_VT23613]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._Reference23612_VT23613 ADD CONSTRAINT
	PK__Reference23612_VT23613 PRIMARY KEY NONCLUSTERED 
	(
	_Reference23612_IDRRef,
	_KeyField,
	_LineNo23614
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._Reference23612_VT23613 SET (LOCK_ESCALATION = TABLE)
COMMIT
End

IF OBJECT_ID('dbo.[PK__Reference114_VT25126]','PK') IS NULL 
Begin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo._Reference114_VT25126 ADD CONSTRAINT
	PK__Reference114_VT25126 PRIMARY KEY NONCLUSTERED 
	(
	_Reference114_IDRRef,
	_KeyField
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE dbo._Reference114_VT25126 SET (LOCK_ESCALATION = TABLE)
COMMIT
End