USE [triovist_repl]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [_AccumRg21407_Custom1]    Script Date: 26.05.2021 17:46:52 ******/
CREATE NONCLUSTERED INDEX [_AccumRg21407_Custom1] ON [dbo].[_AccumRg21407]
(
	[_Fld21408RRef] ASC,
	[_Period] ASC,
	[_RecorderTRef] ASC,
	[_RecorderRRef] ASC,
	[_LineNo] ASC,
	[_Fld21410_TYPE] ASC,
	[_Fld21410_RTRef] ASC,
	[_Fld21410_RRRef] ASC,
	[_Fld21411] ASC,
	[_Fld21442] ASC,
	[_Fld21443RRef] ASC,
	[_Fld21616] ASC,
	[_Fld21982] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


/****** Object:  Index [CustomIndex_25104]    Script Date: 26.05.2021 17:48:50 ******/
CREATE NONCLUSTERED INDEX [CustomIndex_25104] ON [dbo].[_AccumRg25104]
(
	[_Fld25105RRef] ASC,
	[_Period] ASC
)
INCLUDE([_RecordKind],[_Fld25107],[_Fld25108],[_Fld25201]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



/****** Object:  Index [CUSTOM_25110_1]    Script Date: 26.05.2021 17:49:42 ******/
CREATE NONCLUSTERED INDEX [CUSTOM_25110_1] ON [dbo].[_AccumRg25110]
(
	[_Fld25111RRef] ASC,
	[_Period] ASC,
	[_Fld25202] ASC,
	[_Fld25112RRef] ASC
)
INCLUDE([_RecorderTRef],[_RecorderRRef],[_LineNo],[_Active],[_RecordKind],[_Fld25113],[_Fld25203]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


/****** Object:  Index [_AccumRgT21444_1]    Script Date: 26.05.2021 17:55:23 ******/
CREATE CLUSTERED INDEX [_AccumRgT21444_1] ON [dbo].[_AccumRgT21444]
(
	[_Period] ASC,
	[_Fld21408RRef] ASC,
	[_Fld21410_TYPE] ASC,
	[_Fld21410_RTRef] ASC,
	[_Fld21410_RRRef] ASC,
	[_Fld23568RRef] ASC,
	[_Fld21424] ASC,
	[_Splitter] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [_InfoRg21711_Custom1]    Script Date: 07.06.2021 0:40:22 ******/
CREATE NONCLUSTERED INDEX [_InfoRg21711_Custom1] ON [dbo].[_InfoRg21711]
(
	[_Fld25549] ASC,
	[_Fld26708RRef] ASC
)INCLUDE([_Period])WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


/****** Object:  Index [_InfoRg22353_1]    Script Date: 26.05.2021 18:04:08 ******/
CREATE NONCLUSTERED INDEX [_InfoRg22353_1] ON [dbo].[_InfoRg22353]
(
	[_Fld22354] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO
/****** Object:  Index [_InfoRg23320_Custom1]    Script Date: 07.06.2021 0:40:22 ******/
CREATE NONCLUSTERED INDEX [_InfoRg23320_Custom1] ON [dbo].[_InfoRg23320]
(
	[_Fld23322RRef] ASC,
	[_Fld23321] ASC,
	[_Fld23333] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [_InfoRg23830_Custom1]    Script Date: 01.06.2021 13:48:04 ******/
CREATE NONCLUSTERED INDEX [_InfoRg23830_Custom1] ON [dbo].[_InfoRg23830]
(
	[_Fld23833RRef] ASC,
	[_Fld23832] ASC,
	[_Fld23831RRef] ASC,
	[_Fld23834] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


SET ANSI_PADDING ON
GO

/****** Object:  Index [_InfoRg23830_Custom2]    Script Date: 24.06.2021 16:53:45 ******/
CREATE NONCLUSTERED INDEX [_InfoRg23830_Custom2] ON [dbo].[_InfoRg23830]
(
	[_Fld23833RRef] ASC,
	[_Fld23832] DESC
)
INCLUDE([_Fld23831RRef],[_Fld23834]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [_Reference112_5]    Script Date: 26.05.2021 18:05:16 ******/
CREATE NONCLUSTERED INDEX [_Reference112_5] ON [dbo].[_Reference112]
(
	[_Fld25155] ASC,
	[_IDRRef] ASC,
	[_Fld2785RRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [_Reference112_6]    Script Date: 26.05.2021 18:05:27 ******/
CREATE NONCLUSTERED INDEX [_Reference112_6] ON [dbo].[_Reference112]
(
	[_Fld25552] ASC,
	[_IDRRef] ASC,
	[_Fld2785RRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

--replace
CREATE NONCLUSTERED INDEX [_Reference149_Custom1] ON [dbo].[_Reference149]
(
	[_Code] ASC
)INCLUDE ([_IDRRef],[_Fld3480],[_Fld3489RRef],[_Fld3526RRef]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [_Reference149_Custom2] ON [dbo].[_Reference149]
(
	[_Fld3480] ASC
)INCLUDE ([_IDRRef],[_Code],[_Fld3489RRef],[_Fld3526RRef]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [_Reference226_6]    Script Date: 26.05.2021 18:06:37 ******/
CREATE NONCLUSTERED INDEX [_Reference226_Custom1] ON [dbo].[_Reference226]
(
	[_Fld19544] ASC
) INCLUDE([_IDRRef]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


/****** Object:  Index [_Reference256_2]    Script Date: 26.05.2021 18:07:01 ******/
CREATE NONCLUSTERED INDEX [_Reference256_Custom2] ON [dbo].[_Reference256]
(
	[_Marked] ASC,
	[_OwnerID_TYPE] ASC,
	[_OwnerID_RTRef] ASC,
	[_OwnerID_RRRef] ASC,
	[_Fld6003RRef] ASC
)
INCLUDE([_IDRRef],[_Fld6000],[_Fld6006],[_Fld6001],[_Fld6002],[_Fld6009]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO





SET ANSI_PADDING ON
GO
/****** Object:  Index [_Reference114_VT23370_SK]    Script Date: 07.06.2021 0:40:21 ******/
CREATE CLUSTERED INDEX [_Reference114_VT23370_SK] ON [dbo].[_Reference114_VT23370]
(
	[_Reference114_IDRRef] ASC,
	[_KeyField] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO
/****** Object:  Index [_Reference114_VT25126_SK]    Script Date: 07.06.2021 0:40:21 ******/
CREATE CLUSTERED INDEX [_Reference114_VT25126_SK] ON [dbo].[_Reference114_VT25126]
(
	[_Reference114_IDRRef] ASC,
	[_KeyField] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO
/****** Object:  Index [_Reference23294_VT23309_SK]    Script Date: 07.06.2021 0:40:22 ******/
CREATE CLUSTERED INDEX [_Reference23294_VT23309_SK] ON [dbo].[_Reference23294_VT23309]
(
	[_Reference23294_IDRRef] ASC,
	[_KeyField] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO
/****** Object:  Index [_Reference23612_VT23613_SK]    Script Date: 07.06.2021 0:40:22 ******/
CREATE CLUSTERED INDEX [_Reference23612_VT23613_SK] ON [dbo].[_Reference23612_VT23613]
(
	[_Reference23612_IDRRef] ASC,
	[_KeyField] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



SET ANSI_PADDING ON
GO

/****** Object:  Index [_Reference23612_VT23613_Custom1]    Script Date: 08.06.2021 17:54:12 ******/
CREATE NONCLUSTERED INDEX [_Reference23612_VT23613_Custom1] ON [dbo].[_Reference23612_VT23613]
(
	[_Reference23612_IDRRef] ASC,
	[_Fld25265] ASC,
	[_Fld23615] ASC
)
INCLUDE([_Fld23617],[_Fld23618]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [_Reference226_Custom1]    Script Date: 08.06.2021 17:56:57 ******/
CREATE NONCLUSTERED INDEX [_Reference226_Custom2] ON [dbo].[_Reference226]
(
	[_Fld23620RRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO




use [triovist_repl];
GO
use [master];
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_AccumRg21407] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_AccumRg25104] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_AccumRg25110] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_AccumRgT21444] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Const21165] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Const21167] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Const21336] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Const21338] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Const21579] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_InfoRg22353] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_InfoRg23830] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_InfoRg24088] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_InfoRgSL26678] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference112] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference114] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference114_VT23370] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference114_VT25126] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference149] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference226] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference23294] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference23294_VT23309] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference23294_VT26527] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference23612] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference23612_VT23613] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference256] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference99] 
WITH FULLSCAN


dbcc freeproccache