USE [triovist_repl]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [_AccumRg21407_Custom1]    Script Date: 26.05.2021 17:46:52 ******/
CREATE NONCLUSTERED INDEX [_AccumRg21407_Custom1] ON [dbo].[_AccumRg21407]
(
	[_Fld21408RRef] ASC,
	[_Period] ASC,
	[_RecorderTRef] ASC,
	[_RecorderRRef] ASC,
	[_LineNo] ASC,
	[_Fld21410_TYPE] ASC,
	[_Fld21410_RTRef] ASC,
	[_Fld21410_RRRef] ASC,
	[_Fld21411] ASC,
	[_Fld21442] ASC,
	[_Fld21443RRef] ASC,
	[_Fld21616] ASC,
	[_Fld21982] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


/****** Object:  Index [CustomIndex_25104]    Script Date: 26.05.2021 17:48:50 ******/
CREATE NONCLUSTERED INDEX [CustomIndex_25104] ON [dbo].[_AccumRg25104]
(
	[_Fld25105RRef] ASC,
	[_Period] ASC
)
INCLUDE([_RecordKind],[_Fld25107],[_Fld25108],[_Fld25201]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



/****** Object:  Index [CUSTOM_25110_1]    Script Date: 26.05.2021 17:49:42 ******/
CREATE NONCLUSTERED INDEX [CUSTOM_25110_1] ON [dbo].[_AccumRg25110]
(
	[_Fld25111RRef] ASC,
	[_Period] ASC,
	[_Fld25202] ASC,
	[_Fld25112RRef] ASC
)
INCLUDE([_RecordKind],[_Fld25113],[_Fld25203]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


/****** Object:  Index [_AccumRgT21444_1]    Script Date: 26.05.2021 17:55:23 ******/
/* CREATE NONCLUSTERED INDEX [_AccumRgT21444_1] ON [dbo].[_AccumRgT21444]
(
	[_Period] ASC,
	[_Fld21408RRef] ASC,
	[_Fld21410_TYPE] ASC,
	[_Fld21410_RTRef] ASC,
	[_Fld21410_RRRef] ASC,
	[_Fld23568RRef] ASC,
	[_Fld21424] ASC,
	[_Splitter] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO */


/****** Object:  Index [_InfoRg22353_1]    Script Date: 26.05.2021 18:04:08 ******/
/* CREATE NONCLUSTERED INDEX [_InfoRg22353_1] ON [dbo].[_InfoRg22353]
(
	[_Fld22354] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO */


/****** Object:  Index [_InfoRgSL26678_1]    Script Date: 26.05.2021 18:05:00 ******/
/* CREATE NONCLUSTERED INDEX [_InfoRgSL26678_1] ON [dbo].[_InfoRgSL26678]
(
	[_Fld14558RRef] ASC,
	[_Period] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO */



/****** Object:  Index [_Reference112_5]    Script Date: 26.05.2021 18:05:16 ******/
CREATE NONCLUSTERED INDEX [_Reference112_5] ON [dbo].[_Reference112]
(
	[_Fld25155] ASC,
	[_IDRRef] ASC,
	[_Fld2785RRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [_Reference112_6]    Script Date: 26.05.2021 18:05:27 ******/
CREATE NONCLUSTERED INDEX [_Reference112_6] ON [dbo].[_Reference112]
(
	[_Fld25552] ASC,
	[_IDRRef] ASC,
	[_Fld2785RRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

/****** Object:  Index [_Reference149_4]    Script Date: 26.05.2021 18:05:57 ******/
CREATE NONCLUSTERED INDEX [_Reference149_4] ON [dbo].[_Reference149]
(
	[_Code] ASC,
	[_IDRRef] ASC,
    [_Fld3489RRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


/****** Object:  Index [_Reference149_7]    Script Date: 26.05.2021 18:06:10 ******/
CREATE NONCLUSTERED INDEX [_Reference149_7] ON [dbo].[_Reference149]
(
	[_Fld3480] ASC,
	[_IDRRef] ASC,
    [_Fld3489RRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


/****** Object:  Index [_Reference226_6]    Script Date: 26.05.2021 18:06:37 ******/
CREATE NONCLUSTERED INDEX [_Reference226_6] ON [dbo].[_Reference226]
(
	[_Fld19544] ASC,
	[_IDRRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


/****** Object:  Index [_Reference256_2]    Script Date: 26.05.2021 18:07:01 ******/
CREATE NONCLUSTERED INDEX [_Reference256_2] ON [dbo].[_Reference256]
(
	[_OwnerID_TYPE] ASC,
	[_OwnerID_RTRef] ASC,
	[_OwnerID_RRRef] ASC,
	[_Description] ASC,
	[_IDRRef] ASC,
	[_Marked] ASC
)
INCLUDE([_Fld6003RRef],[_Fld6006],[_Fld6000]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


use [triovist_repl];
GO
use [master];
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_AccumRg21407] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_AccumRg25104] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_AccumRg25110] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_AccumRgT21444] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Const21165] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Const21167] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Const21336] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Const21338] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Const21579] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_InfoRg22353] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_InfoRg23830] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_InfoRg24088] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_InfoRgSL26678] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference112] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference114] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference114_VT23370] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference114_VT25126] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference149] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference226] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference23294] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference23294_VT23309] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference23294_VT26527] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference23612] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference23612_VT23613] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference256] 
WITH FULLSCAN
GO
use [triovist_repl]
GO
UPDATE STATISTICS [dbo].[_Reference99] 
WITH FULLSCAN


dbcc freeproccache